### ISSUE TITLE
Cannot install pipeline-live Windows

### ISSUE THREAD

**Issue by aaronsthiel** [alpacahq/pipeline-live#27]
I just installed pylivetrader using 3 channels (conda-forge, Quantopian, alpacahq) and conda create -n pylivetraderenv pylivetrader.  The environment is pretty outdated (Python 3.5.5, Pylivetrader 0.0.20, Websockets 6.0) but it appears to work on the very basic algos.  However, I just tried to pip install pipeline-live but it failed to install.  The install seemed to go pretty far but the error came right at the end.  I'll paste the error below.  Any thoughts or help would be greatly appreciated!

sing cached tables-3.6.1.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Owner\Anaconda3\envs\pylivetraderenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Owner\\AppData\\Local\\Temp\\pip-install-f95bg5wp\\tables\\setup.py'"'"'; __file__='"'"'C:\\Users\\Owner\\AppData\\Local\\Temp\\pip-install-f95bg5wp\\tables\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Owner\AppData\Local\Temp\pip-pip-egg-info-qz8_dtxw'
         cwd: C:\Users\Owner\AppData\Local\Temp\pip-install-f95bg5wp\tables\
    Complete output (29 lines):
    * Using Python 3.5.5 | packaged by conda-forge | (default, Jul 24 2018, 01:52:17) [MSC v.1900 64 bit (AMD64)]
    * USE_PKGCONFIG: False
    * Found conda env: ``C:\Users\Owner\Anaconda3\envs\pylivetraderenv``
    Traceback (most recent call last):
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Owner\AppData\Local\Temp\pip-install-f95bg5wp\tables\setup.py", line 635, in <module>
        libraries=(package.library_name,))
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\distutils\ccompiler.py", line 791, in has_function
        objects = self.compile([fname], include_dirs=include_dirs)
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\Owner\Anaconda3\envs\pylivetraderenv\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by shlomikushchi** [comment]
Hi, 
it looks like you need the visual studio build tools (https://visualstudio.microsoft.com/visual-cpp-build-tools/)
but, I would try installing everything on an updated environment.

**Comment by aaronsthiel** [comment]
Thanks, I'll do both.

**Comment by Nicosunaa** [comment]
Hi! I am getting the same error but I am trying to still pipeline-live in python 3.6 on a MAC. is there any way I could install it without the visual studio build tools?

**Comment by shlomikushchi** [comment]
what are the errors you get?

**Comment by Nicosunaa** [comment]
I tried to install it using conda install in a python 3.6 environment and it appears the following:

PackagesNotFoundError: The following packages are not available from current channels:

  - pipeline-live

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

I also tried to install it using pip (python3.6) install but it does not appear as a package when working in PyCharm

**Comment by shlomikushchi** [comment]
Hi,
I just installed it using pip in the command line.
try using the command line and run: `pip install pipeline-live`
