### ISSUE TITLE
Could not find a version that satisfies the requirement pandas==0.22.0

### ISSUE THREAD

**Issue by p595285902** [alpacahq/pipeline-live#31]
Hi, I am trying to install the pipeline-live, but having following error.
```
  ERROR: Command errored out with exit status 1: 'c:\users\wu\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Wu\\AppData\\Local\\Temp\\pip-install-f_r35rfb\\numpy_67c03d43693c4841981441e89e071a43\\setup.py'"'"'; __file__='"'"'C:\\Users\\Wu\\AppData\\Local\\Temp\\pip-install-f_r35rfb\\numpy_67c03d43693c4841981441e89e071a43\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Wu\AppData\Local\Temp\pip-record-7t5te5_v\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Wu\AppData\Local\Temp\pip-build-env-7m8umo9x\overlay' --compile --install-headers 'C:\Users\Wu\AppData\Local\Temp\pip-build-env-7m8umo9x\overlay\Include\numpy' Check the logs for full command output.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz#sha256=44a94091dd71f05922eec661638ec1a35f26d573c119aa2fad964f10a2880e6c (from https://pypi.org/simple/pandas/). Command errored out with exit status 1: 'c:\users\wu\appdata\local\programs\python\python39\python.exe' 'c:\users\wu\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Wu\AppData\Local\Temp\pip-build-env-7m8umo9x\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython 'numpy==1.9.3; python_version=='"'"'3.5'"'"'' 'numpy==1.12.1; python_version=='"'"'3.6'"'"'' 'numpy==1.13.1; python_version>='"'"'3.7'"'"'' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pandas==0.22.0 (from pipeline-live)
ERROR: No matching distribution found for pandas==0.22.0
```
I am able to do `pip install pandas` to install the latest, but seems like the library only needs pandas 0.22.0
Any suggestions?

Also is there a way for me to filter all the stocks every 4hours?

Thanks!

**Comment by shlomikushchi** [comment]
Hi, that's because you are using python 3.9. this package works with python 3.6

**Comment by shlomikushchi** [comment]
basically every time you run this you get the filtering you wanted.. so this should work even every four hours, yes

**Comment by p595285902** [comment]
Thanks for your quick reply!
Sorry, I was thinking about couple questions, and some how the 4 hours interval question gets written down...
I was wondering if filtering could be applied during back testing using` alpaca_backtrader_api`. If so, is there an example? 

I am facing another issue after I changed to 3.6 and resolved another issue where C++ 14 not found. 
```
      File "c:\users\wu\appdata\local\programs\python\python36\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check      
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('c:\\users\\wu\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

[link](https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an) says numpy 1.19.3 works, but your setup.py requires 1.19.4. Any suggestions?

**Comment by shlomikushchi** [comment]
pipeline-live works with pylivetrader or as stand alone. it cannot work with alpaca-backtrader.
for backtesting abilities and filtering abilities checkout zipline-trader/
When does this issue with numpy occurs? if it persists install 1.19.3 (or try 1.19.5 which was released recently)

**Comment by p595285902** [comment]
I tried install 1.19.3 first then run the command `pip install pipeline-live`.
But it will try to get 1.19.4 and then fail.
```
C:\Wu\stock\alpacha> pip install pipeline-live
Collecting pipeline-live
  Using cached https://files.pythonhosted.org/packages/5d/33/85096a4b234adbfb7aa7fcbcb2ddad7e57f3d5122aad1dfeb184e1e92146/pipeline_live-0.1.12-py3-none-any.whl
Requirement already satisfied: pandas==0.22.0 in c:\users\wu\appdata\local\programs\python\python36\lib\site-packages (from pipeline-live)
Requirement already satisfied: lxml>=4.6.2 in c:\users\wu\appdata\local\programs\python\python36\lib\site-packages (from pipeline-live)
Requirement already satisfied: scipy<=1.6.0 in c:\users\wu\appdata\local\programs\python\python36\lib\site-packages (from pipeline-live)
Collecting numpy==1.19.4 (from pipeline-live)
  Using cached https://files.pythonhosted.org/packages/33/26/c448c5203823d744b7e71b81c2b6dcbcd4bff972897ce989b437ee836b2b/numpy-1.19.4-cp36-cp36m-win_amd64.whl...
```

**Comment by shlomikushchi** [comment]
install pipeline-live and after that install numpy 1.19.3

**Comment by p595285902** [comment]
Here what I am running:
```
pip install pipeline-live
pip install numpy==1.19.3
```
then getting the following error when I tried to run the sample code in the readme:
```
Traceback (most recent call last):
  File "c:/Wu/stock/alpacha/pipeline_liveTest.py", line 1, in <module>
    from pipeline_live.engine import LivePipelineEngine
ModuleNotFoundError: No module named 'pipeline_live'
```

**Comment by shlomikushchi** [comment]
then you installed it in a different interpreter than the one you use for `
pipeline_liveTest.py`

**Comment by shlomikushchi** [comment]
then you installed it in a different interpreter than the one you use for `pipeline_liveTest.py`

**Comment by p595285902** [comment]
Is there a way to confirm? I am running in VS Code and didn't change interpreter during those commands.
![image](https://user-images.githubusercontent.com/2326686/106057641-4570b880-60be-11eb-8f56-5117074c06b3.png)
![image](https://user-images.githubusercontent.com/2326686/106057694-528da780-60be-11eb-84b2-249684ed00e6.png)

**Comment by camelpac** [comment]
closing for lack of activity. do let us know if it's still an issue.
