### ISSUE TITLE
Running the example in the README results with an error

### ISSUE THREAD

**Issue by idanre1** [alpacahq/pipeline-live#4]
Hi
I have running ubuntu 18 LTS
I have installed pipeline-live using the following:
sudo apt install python3 python3-pip python3-tk
pip3 install pipeline-live

then I am trying to run the example in the README of the github which result with the following error
sudo apt install python3 python3-pip python3-tk
python3 pipeline.py 
Traceback (most recent call last):
  File "pipeline.py", line 1, in <module>
    from pipeline_live.engine import LivePipelineEngine
  File "/home/idan/.local/lib/python3.6/site-packages/pipeline_live/engine.py", line 11, in <module>
    from zipline.lib.adjusted_array import ensure_adjusted_array, ensure_ndarray
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/utils/run_algo.py", line 20, in <module>
    from zipline.finance import metrics
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/finance/metrics/__init__.py", line 43, in <module>
    from .tracker import MetricsTracker
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/finance/metrics/tracker.py", line 19, in <module>
    from ..ledger import Ledger
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/finance/ledger.py", line 28, in <module>
    from zipline.finance.transaction import Transaction
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/finance/transaction.py", line 20, in <module>
    from zipline.protocol import DATASOURCE_TYPE
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/protocol.py", line 20, in <module>
    from .utils.enum import enum
  File "/home/idan/.local/lib/python3.6/site-packages/zipline/utils/enum.py", line 43, in <module>
    method='bfill',
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/series.py", line 3325, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3689, in reindex
    fill_value, copy).__finalize__(self)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3702, in _reindex_axes
    tolerance=tolerance, method=method)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3622, in reindex
    tolerance=tolerance)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3248, in get_indexer
    indexer = self._get_fill_indexer(target, method, limit, tolerance)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3278, in _get_fill_indexer
    limit)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3300, in _get_fill_indexer_searchsorted
    side)
  File "/home/idan/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4200, in _searchsorted_monotonic
    raise ValueError('index must be monotonic increasing or decreasing')
ValueError: index must be monotonic increasing or decreasing

please help

**Comment by idanre1** [comment]
Found the issue
zipline is a dependency of pipeline-live
apparently acodring to the release notes zipline should only wotk with specific versions of pandas and numpy.
From release notes of version 1.3.0: https://github.com/quantopian/zipline/releases
As part of this release, we're now building and testing Zipline with two package configurations:

    "Stable", using numpy version 1.11 and pandas version 0.18.1.
    "Latest", using numpy version 1.14 and pandas version 0.22.0.

Other combinations of numpy and pandas may work, but these package sets will be built and tested during our normal development cycle.

I would suggest changing the README file for making sure the required pandas and numpy are installed prior to installing pipeline-live

Idan

**Comment by anthonyPlexuss** [comment]
Hi there, I'm new to quantopian. trying to run this example on Ubuntu18 using the docker image of pylivetrader. I'm getting the same error 

`ValueError: numpy.ufunc has the wrong size, try recompiling`

please help.
