### ISSUE TITLE
engine.py exception

### ISSUE THREAD

**Issue by carles-estevadeordal** [alpacahq/pipeline-live#7]
Traceback (most recent call last):
  File "/opt/conda/bin/pylivetrader", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pylivetrader/__main__.py", line 161, in run
    algorithm.run(retry=ctx.retry)
  File "/opt/conda/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 271, in run
    return self.executor.run(retry=retry)
  File "/opt/conda/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 119, in run
    algo.before_trading_start(self.current_data)
  File "/opt/conda/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 244, in before_trading_start
    self._before_trading_start(self, data)
  File "reversion.py", line 97, in before_trading_start
    context.my_output = pipeline_output('my_pipeline')
  File "/opt/conda/lib/python3.6/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 1077, in pipeline_output
    output = eng.run_pipeline(self._pipelines[name])
  File "/opt/conda/lib/python3.6/site-packages/pipeline_live/engine.py", line 45, in run_pipeline
    tz='utc')
  File "pandas/tslib.pyx", line 291, in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:9120)
TypeError: __new__() takes at least 2 positional arguments (1 given)

**Comment by garyha** [comment]
```
$ pip install pipdeptree
$ pipdeptree -p pylivetrader
```

**Comment by carles-estevadeordal** [comment]
This fixed the issue, thanks!
